[tool.poetry]
name = "mcssl"
version = "0.1.0"
description = "Minimal Client Server Socket Library"
authors = ["ars6502 <ars6502@localhost>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
